tutu/config/routes.rb
Rails.application.routes.draw do
  resources :railway_stations
  resources :trains
  resources :routes
  get 'welcome/index'
  root 'welcome#index'

end

tutu/app/models/railway_station.rb
class RailwayStation < ActiveRecord::Base
  has_many :trains
  has_many :railway_stations_routes
  has_many :routes, through: :railway_stations_routes
  
  validates :title, presence: true
end

tutu/app/models/railway_stations_route.rb
class RailwayStationsRoute < ActiveRecord::Base
  belongs_to :railway_station
  belongs_to :route
end

tutu/app/models/route.rb
class Route < ActiveRecord::Base
  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains
  
  validates :title, presence: true
end

tutu/app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :train
  belongs_to :start_station, class_name: 'RailwayStation', foreign_key: :start_station_id
  belongs_to :end_station, class_name: 'RailwayStation', foreign_key: :end_station_id
  belongs_to :user

  validates :train, presence: true
  validates :start_station, presence: true
  validates :end_station, presence: true
  validates :user, presence: true
end

tutu/app/models/train.rb
class Train < ActiveRecord::Base
  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route
  has_many :tickets
  # has_many :users, through: :tickets

  validates :number, presence: true#, format: {with: /^[а-яa-z\d]{3}-?[а-яa-z\d]{2}$/i, uniqueness: true}
end

tutu/app/models/user.rb
class User < ActiveRecord::Base
  has_many :tickets
  # has_many :trains, through: :tickets
  
  validates :name, presence: true
end

tutu/app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def edit
  end

  def create
    @route = Route.new(route_params)
    if @route.save
      redirect_to @route, notice: "Путь успешно создан."
    else
      render :new
    end
  end

  def update
    if @route.update(route_params)
      redirect_to @route, notice: "Путь успешно изменен."
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path, notice: "Путь успешно удален."
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(:title)
  end
end

tutu/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: [:show, :edit, :update, :destroy]

  def index
    @trains = Train.all
  end

  def show
  end

  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)

    if @train.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to @train
    else
      render :edit
    end
  end

  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private

  def set_train
    @train = Train.find(params[:id])
  end

  def train_params
    params.require(:train).permit(:number)
  end
end

tutu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutu11</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

tutu/app/views/railway_stations/_form.html.erb
<%= form_for(@railway_station) do |f| %>
  <% if @railway_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@railway_station.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
      <% @railway_station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Создать'%>
  </div>
<% end %>

tutu/app/views/railway_stations/edit.html.erb
<h1>Редактировать станцию</h1>

<%= render 'form' %>

<%= link_to 'Показать', @railway_station %> |
<%= link_to 'Назад', railway_stations_path %>

tutu/app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список станций</h1>

<table>
  <thead>
    <tr>
      <th>Название</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Показать', railway_station %></td>
        <td><%= link_to 'Редактировать', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Удалить', railway_station, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить станцию', new_railway_station_path %>

tutu/app/views/railway_stations/new.html.erb
<h1>Добавить станцию</h1>

<%= render 'form' %>

<%= link_to 'Назад', railway_stations_path %>

tutu/app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Редактировать', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Назад', railway_stations_path %>

tutu/app/views/routes/_form.html.erb
<%= form_for(@route) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Имя' %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

tutu/app/views/routes/edit.html.erb
<h1>Изменить путь</h1>

<%= render 'form' %>

<%= link_to 'Назад', routes_path %>

tutu/app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список путей</h1>

<table>
  <thead>
  <tr>
    <th>Название</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
      <tr>
        <td><%= route.title %></td>
        <td><%= link_to 'Показать', route %></td>
        <td><%= link_to 'Редактировать', edit_route_path(route) %></td>
        <td><%= link_to 'Удалить', route, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить путь', new_route_path %>

tutu/app/views/routes/new.html.erb
<h1>Добавить путь</h1>

<%= render 'form' %>

<%= link_to 'Назад', routes_path %>

tutu/app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Название:</strong>
  <%= @route.title %>
</p>

<%= link_to 'Редактировать', edit_route_path(@route) %> |
<%= link_to 'Назад', routes_path %>

tutu/app/views/trains/_form.html.erb
<%= form_for(@train) do |f| %>
  <% if @train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
      <% @train.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

tutu/app/views/trains/edit.html.erb
<h1>Изменить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

tutu/app/views/trains/index.html (denis-ProBook's conflicted copy 2016-02-08).erb
<p id="notice"><%= notice %></p>

<h1>Списко поездов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Показать', train %></td>
        <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway station', new_railway_station_path %>

tutu/app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Список поездов</h1>

<table>
  <thead>
  <tr>
    <th>Номер</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Показать', train %></td>
        <td><%= link_to 'Редактировать', edit_train_path(train) %></td>
        <td><%= link_to 'Удалить', train, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Добавить поезд', new_train_path %>

tutu/app/views/trains/new.html.erb
<h1>Добавить поезд</h1>

<%= render 'form' %>

<%= link_to 'Назад', trains_path %>

tutu/app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Номер:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Редактировать', edit_train_path(@train) %> |
<%= link_to 'Назад', trains_path %>

tutu/app/views/welcome/index.html.erb
<h1>Привет, Rails!</h1>

<%= link_to "Список станций", railway_stations_path %>